version: 2
jobs:
  run:
    machine:
      - image: ubuntu-2204:current
    steps:
      - checkout
      - run: DATACENTERS=fr,gra,rbx,sbg PLAN_CODE=22sk010 ./bin/check.sh

workflows:
  version: 2
  build:
    jobs:
      - run:
         filters:
          branches:
            only: main
         context:
         - opsgenie
  run:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - run
