version: 2
jobs:
  run:
    machine:
    - image: ubuntu-2204:current
    steps:
    - checkout
    - run: ./hack/check.sh

workflows:
  version: 2
  build:
    jobs:
    - run:
        filters:
          branches:
            only: master
       context:
       - kimsufi-notifier
  run:
    triggers:
    - schedule:
        cron: "0 * * * *"
        filters:
          branches:
            only:
            - master
    jobs:
    - run
