name: 'run'
on:
  schedule:
    # run every 5 minute; shortest interval for github actions
    # see: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onschedule
    - cron:  '*/5 * * * *'

jobs:
  run:
    name: 'run'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check
        env:
          COUNTRY: ${{ secrets.COUNTRY }}
          HARDWARE: ${{ secrets.HARDWARE }}
          SMS_USER: ${{ secrets.SMS_USER }}
          SMS_PASS: ${{ secrets.SMS_PASS }}
        run: hack/check.sh
